CONSUMER_ID = 1484
CONSUMER_SECRET = '5nuryGqaNCtJsJvz4XvrTzfXvsbPNvKu'
APP_SECRET = 'happyapps'

ANDREW_CONSUMER_ID = 1486
ANDREW_CONSUMER_SECRET = 'Kv3hAtR8NagKPAvKEeGtErNkTNtrxKQx'
ANDREW_APP_SECRET = 'unhappyapps'
